### ISSUE TITLE
Roles with different capitilization aren't found

### ISSUE THREAD

**Issue by talios0** [talios0/Form2RoleBot#17]
The program should find the pre-existing role, no matter how the information from the attached Google Sheets is formatted. As of now, it'll create a new role instead, which has the potential for creating problems if an "Other" field or text field is used.

**Comment by Lawrence-O** [comment]
why don't we just remove the other field?

**Comment by talios0** [comment]
Due to the way Discord Roles work, it would be incredibly costly performance wise to implement this feature.
