### ISSUE TITLE
Roles not updating?

### ISSUE THREAD

**Issue by MoXAriApph** [talios0/Form2RoleBot#26]
**Describe the bug**

**To Reproduce**
1. Go to: Bot Config/Console
2. Put in form info and tokens
3. Load a range from a subsheet (Currently loading 'Assignment'!A2:B1000)
4. Names are in A2:A1000
5. Roles are in B2:B1000
6. Roles will not update but discord names are fully recognized
 
**Expected behavior**
People should be assigned roles properly

**Screenshots**
https://imgur.com/a/8aNhFd0

**Desktop (please complete the following information):**
- Form2Role Bot v0.3.0a3

**Comment by talios0** [comment]
I'm sorry that your having this issue. If at all possible, can you post an image of your configs with the token, API Key and SheetsID removed? It is also possible that the bot doesn't have permission to create and assign roles, so try checking that first.

**Comment by MoXAriApph** [comment]
Bot is higher than the roles that need to be given along with having the correct permissions, it might be a config issue? I'm probably doing it wrong
https://imgur.com/a/bQutn1q

**Comment by talios0** [comment]
Everything should work if you change the range value to "Range": "A2:B",

**Comment by MoXAriApph** [comment]
Will that work if it's a sub-sheet? Or do I need to order the sub sheets a certain way / change the sheet ID to make it use the right one
https://imgur.com/a/uovyjau

**Comment by talios0** [comment]
For now, make the subsheet with the responses the first one. To be honest, I never considered that someone may have more than the auto-generated ones so I'll try to add the option to choose in the future.

**Comment by MoXAriApph** [comment]
It currently still isn't doing roles, after changing the range and making the sub-sheet the first one in the list

**Comment by talios0** [comment]
Just noticed something. You have the roles ending 1 before the last. Since you're only checking A (for username) and B (for role) you should set RolesEndBefore to 0. You would only use it if there was a nickname field at the end.

**Comment by MoXAriApph** [comment]
🎉🎉 doing that fixed it, tyty x=x
