### ISSUE TITLE
Error (without roles?)

### ISSUE THREAD

**Issue by skylatian** [talios0/Form2RoleBot#28]
![Screenshot (14)](https://user-images.githubusercontent.com/53362705/95545489-dc502280-09b2-11eb-9049-38b02c6ef9d6.png)
Bot throws this error (I'm assuming it's when roles aren't configured)-is there any way to remove the role functionality entirely? I just need it for nicknames per user.

**Comment by talios0** [comment]
That's interesting. I'll start working on a solution (should be done soon). Could you possibly provide your google sheets config (without api key and sheets id)? Thanks!

**Comment by talios0** [comment]
I just updated the program for support for nickname only use. My own testing brought up no issues. https://github.com/talios0/Form2RoleBot/releases/tag/0.3.3 . If have any questions, let me know!

**Comment by skylatian** [comment]
That worked! Thank you so much. Here are the files that I used previously just in case you're interested in them. Had to change them to txt to upload here. Let me know if anything was off, could've been a , or "" mistake on my part. I'll play with role assignments now to see if they work.
 
[roleGroups.txt](https://github.com/talios0/Form2RoleBot/files/5366921/roleGroups.txt)
[config.txt](https://github.com/talios0/Form2RoleBot/files/5366918/config.txt)
[googleConfig.txt](https://github.com/talios0/Form2RoleBot/files/5366919/googleConfig.txt)

**Comment by talios0** [comment]
Everything looks good! I hope everything works well from here on out. Don't hesitate to ask any questions. The roleGroups config will only be used if it is enabled in the config. Otherwise, it doesn't do anything.

**Comment by skylatian** [comment]
I do have one question, actually-how does it handle incorrect discord IDs? (if there's something before or after the ID) Will it just skip that one or break the bot?

**Comment by talios0** [comment]
Incorrect IDs are skipped. Basically, the bot looks through the users on the server, if no user matches the ID in the google sheet, it skips it.
