### ISSUE TITLE
Add option to PM users only after nickname/role has been assigned

### ISSUE THREAD

**Issue by skylatian** [talios0/Form2RoleBot#29]
**Additional context**
Maybe have a toggle to PM users only once their nickname/role in a server has been assigned? I'm using the bot for verification through a restricted google form, so users are only able to access the server once their info has been updated. Would this toggle be difficult to do integrate?

Sorry for the basically back-to-back requests, this is a very unique bot!

**Comment by talios0** [comment]
This is a good idea! It shouldn't be too difficult, I should have some time within the next two days to get this implemented properly. Thanks for the feedback!

**Comment by skylatian** [comment]
Awesome! Was going to make a second bot 😅. No rush, thanks for all your help!

**Comment by skylatian** [comment]
Just checking in, how's the update going? Also, do you have a cashapp or venmo I could send a couple bucks through? This is helping me a bunch :)

**Comment by talios0** [comment]
No payment necessary, I have unfortunately not had any time to work on the update, but I will be able to work on it today. I would expect it to be finished today or tomorrow. Sorry for the wait!

**Comment by skylatian** [comment]
No worries! Thanks for the help. 😄

**Comment by talios0** [comment]
Update complete! There's now an option to have the bot send out a message after it makes changes to the user. If no changes are made, no message is sent. https://github.com/talios0/Form2RoleBot/releases/tag/0.3.4 . Let me know if you have any questions!

**Comment by skylatian** [comment]
It looks like the PM is only sent if the field isn't blank, right? Does the PMUsers option only affect the welcome message?

**Comment by talios0** [comment]
Yup, that's exactly how it works. The configuration file as a whole needs a bit of a re-work...
