### ISSUE TITLE
Bot crash after start

### ISSUE THREAD

**Issue by iPain3G** [talios0/Form2RoleBot#32]
The bot crash directly after the start but i was able have saved the errormessages.
Something with ther SERVER MEMBERS INTENT function broke the bot. Without this function the bot is running but won't update the user roles. With this function enabled i get the following errormessages and the bot chrash.

Errorlog:
Unbehandelte Ausnahme: System.AggregateException: Mindestens ein Fehler ist aufgetreten. ---> System.ArgumentNullException: Der Wert darf nicht NULL sein.
Parametername: name
   bei Discord.Rest.GuildHelper.<CreateRoleAsync>d__20.MoveNext()
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   bei System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   bei DiscordBot.SheetsFunctionality.<CreateRole>d__3.MoveNext() in E:\Talios0\Form2RoleBot\DiscordBot\SheetsFunctionality.cs:Zeile 87.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei DiscordBot.Sheets.<AssignRoles>d__6.MoveNext() in E:\Talios0\Form2RoleBot\DiscordBot\Sheets.cs:Zeile 95.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei DiscordBot.Sheets.<UpdateRoles>d__5.MoveNext() in E:\Talios0\Form2RoleBot\DiscordBot\Sheets.cs:Zeile 47.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei DiscordBot.Program.<StartAsync>d__4.MoveNext() in E:\Talios0\Form2RoleBot\DiscordBot\Program.cs:Zeile 58.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei DiscordBot.Program.Main(String[] args) in E:\Talios0\Form2RoleBot\DiscordBot\Program.cs:Zeile 22.

**Comment by talios0** [comment]
Sorry for the delay. I am looking into this now. I'll aim to have this fixed today, but no guarantees.

**Comment by taliyos** [comment]
Sorry again for the delay, a fix is just about available (within the next hour). Please re-enable the Guild Members intent on discord.com/developers, or the app won't be able to update.

**Comment by taliyos** [comment]
The update is now live, you can download Form2Role Bot v0.3.5 from [here](https://github.com/talios0/Form2RoleBot/releases/tag/0.3.5) or by going to the releases tab on the repository's main page. Thanks for sending in the issue, Discord's recent API changes made some of the previous code invalid. Please let me know if you experience any further issues!
